default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["mysql_user"] %>
  password: <%= ENV["mysql_pass"] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: Forum_gamer

test:
  <<: *default
  database: test_Forum_gamer

production:
  <<: *default
  database: testig_production
  username: testig
  password: <%= ENV['TESTIG_DATABASE_PASSWORD'] %>
